<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

#### **Exercise 1(Total recall)**

|**Term**|**Brief description**|
|:---|:---|
|Subsetting|Refers to selecting a of data in a list or array|
|Indexing| Refers to selecting a single element from the data in a list or array|
|Slicing| Refers to selecting a range of elements from the data in a list or array|
|Masking| Masking refers to the use of conditions to subset arrays or lists|


#### **Exercise 2(Show me the 'odd' letters)**

In [58]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
str_number_array = np_array_2d[0:10, 0]
number_array = str_number_array.astype(int)
odd_array_checker = number_array%2 > 0
odd_arrays_and_letters = np_array_2d[odd_array_checker]
odd_letters = odd_arrays_and_letters[0:,1]
print(odd_letters)



['A' 'C' 'E' 'G' 'I']


#### **Exercise 3**

In [73]:
np_array_2d = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

np_array_2d[np_array_2d>50]  = 1
np_array_2d[np_array_2d==50] = 0
print(np_array_2d)



[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
